import{S as p,i as c}from"./assets/vendor-5ObWk2rO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();function u(a){const s=`https://pixabay.com/api/?${new URLSearchParams({key:"47659008-74bbb6b2c2d0fee0411ee57da",q:a.trim(),image_type:"photo",orientation:"horizontal",safesearch:!0})}`;return fetch(s,{method:"GET",headers:{Accept:"application/json"}}).then(o=>{if(!o.ok)throw new Error(o.status);return o.json()})}function d(a){return a.map(({webformatURL:r,largeImageURL:s,tags:o,likes:e,views:t,comments:n,downloads:m})=>`<li class="list-item" >
  <a href="${s}" alt="${o}" title=""/>
    <img src="${r}" alt="${o}" class="img-item">
  <div class="list-container">
  <p class="item"><span class="item-text">Likes</span> <span>${e}</span></p>
  <p class="item"><span class="item-text">Wiews</span> <span>${t}</span></p>
  <p class="item"><span class="item-text">Comments</span> <span>${n}</span></p>
  <p class="item"><span class="item-text">Downlods</span> <span>${m}</span></p>
  </div></a>
</li>`).join("")}const f=new p(".gallery a",{captionsData:"alt",captionDelay:250,captionClass:"imageTitle"}),h=document.querySelector(".form"),l=document.querySelector(".gallery"),i=document.querySelector(".loader");h.addEventListener("submit",g);function g(a){a.preventDefault();const r=a.target.elements.search.value.trim();if(console.log(r),l.innerHTML="",i.innerHTML="",!r||r===" "){c.show({message:"Please add request!",position:"center",color:"red"}),l.innerHTML=":(";return}i.classList.remove("hidden"),u(r).then(s=>{console.log(s),s.hits.length?(l.innerHTML=d(s.hits),f.refresh()):(c.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"center",color:"red"}),i.innerHTML="<h1>Error..</h1>")}).catch(s=>{console.log(s.message),c.show({message:`${s.message}`,position:"center",color:"red"})}).finally(()=>{a.target.elements.search.value="",i.classList.add("hidden")})}
//# sourceMappingURL=index.js.map
